### ISSUE TITLE
Suddenly No Batch Process or Batch From Directory

### ISSUE THREAD

**Issue by Marko1985insane** [thygate/stable-diffusion-webui-depthmap-script#176]
First off, what an amazing extension! Thank you. 
My problem: I was using the batch process for quite a while without problem then suddently one day without changing any settings anywhere, it simply stopped working. I would get a 'IndexError: tuple index out of range' error along with a 'ValueError: Number of output components does not match number of values returned from from function f'. Single images still worked however. I didn't change my process in any way. Same kinds of images. Same kinds of sizes etc.

Then more recently, after updating the extension, I can't even load more than one image into the batch process box. If i drag several images over, only one shows up. 

Batch from directory has never worked for me at any point. 

With batch scanning, I get the following error:

OSError: [Errno 22] Invalid argument: "<div class='error'>OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: &#x27;&quot;D:\\\\Documents\\\\FTMV\\\\Misc\\\\Sayin\\&#x27;\\\\One Level in\\\\Automatic Web Downloads\\\\Batch Scan&quot;&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3534/8192 MiB (43.14%)</p></div>"

I am not at all well versed in coding but any help you could offer would be very much appreciated.  Thank you.

**Comment by thygate** [comment]
please post the entire stack trace from the console

**Comment by Marko1985insane** [comment]
Thanks for the quick response. This is what I'm getting from Batch From Directory:

Error completing request
Arguments: (2, None, None, '"C:\\Users\\Marcos\\Downloads\\Art Folder Batch Scan"', '"C:\\Users\\Marcos\\Downloads\\Art Out"', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Marcos\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1085, in run_generate
    image_list = shared.listfiles(depthmap_batch_input_dir)
  File "C:\Users\Marcos\stable-diffusion-webui\modules\shared.py", line 730, in listfiles
    filenames = [os.path.join(dirname, x) for x in sorted(os.listdir(dirname)) if not x.startswith(".")]
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Users\\Marcos\\Downloads\\Art Folder Batch Scan"'

Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: &#x27;&quot;C:\\\\Users\\\\Marcos\\\\Downloads\\\\Art Folder Batch Scan&quot;&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3534/8192 MiB (43.14%)</p></div>"

**Comment by Marko1985insane** [comment]
And this is what I get from the batch process. Although like I said, dragging multiple images into the box results in only one actually appearing there unlike before when they would all be there to see:

Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: &#x27;&quot;C:\\\\Users\\\\Marcos\\\\Downloads\\\\Art Folder Batch Scan&quot;&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3534/8192 MiB (43.14%)</p></div>"
Error completing request
Arguments: (1, None, <tempfile._TemporaryFileWrapper object at 0x0000022F13923340>, '"C:\\Users\\Marcos\\Downloads\\Art Folder Batch Scan"', '"C:\\Users\\Marcos\\Downloads\\Art Out"', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Marcos\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1110, in run_generate
    outputs, mesh_fi, meshsimple_fi = run_depthmap(
ValueError: not enough values to unpack (expected 3, got 2)

Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>ValueError: not enough values to unpack (expected 3, got 2)</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3534/8192 MiB (43.14%)</p></div>"

**Comment by thygate** [comment]
I spotted the bug, working on fix ..

**Comment by Marko1985insane** [comment]
Awesome. Thank you and looking forward to it!

**Comment by thygate** [comment]
I just made the commit with the fix.

>Batch from directory has never worked for me at any point.

What is the problem there ?

**Comment by Marko1985insane** [comment]
So the fix to batch process now indeed allows multiple files to sit in the box again but it still produces an error upon hitting generate. the error I'm getting is:

Error completing request
Arguments: (1, None, [<tempfile._TemporaryFileWrapper object at 0x0000016112AE7F10>, <tempfile._TemporaryFileWrapper object at 0x0000016112AE7FA0>, <tempfile._TemporaryFileWrapper object at 0x0000016112AE7D30>, <tempfile._TemporaryFileWrapper object at 0x00000161D0FCBE20>, <tempfile._TemporaryFileWrapper object at 0x00000161135FF970>, <tempfile._TemporaryFileWrapper object at 0x00000161135FDF60>], '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, True, ['left-right'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, 'u2net', False, 0, 2, False, None, False, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Marcos\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1114, in run_generate
    image = Image.open(img)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x0000016112AE7F10>

Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>UnidentifiedImageError: cannot identify image file &lt;tempfile._TemporaryFileWrapper object at 0x0000016112AE7F10&gt;</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3534/8192 MiB (43.14%)</p></div>"

**Comment by thygate** [comment]
>PIL.UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x0000016112AE7F10>
UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x0000016112AE7F10>

There are more reports of this problem for some users, but I have not found any solution yet ..
It seems like temporary files are not accessible for some reason .. :\

**Comment by Marko1985insane** [comment]
Thanks again for replying. I ran the upgrade and 'Successfully installed pip-23.0.1'. Still got the error that follows my next sentence using batch process. I ran batch process in the extras tab and it worked without problem (Batch from directory still produced the same syntax error. However, it is batch process that would be mist useful to me)

Error completing request
Arguments: (1, None, [<tempfile._TemporaryFileWrapper object at 0x0000021913488130>, <tempfile._TemporaryFileWrapper object at 0x000002191348BF70>, <tempfile._TemporaryFileWrapper object at 0x000002191348A1D0>, <tempfile._TemporaryFileWrapper object at 0x000002191348AE60>], '', '', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, 'u2net', False, 0, 2, False, None, True, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Marcos\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1114, in run_generate
    image = Image.open(img)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x0000021913488130>

Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>UnidentifiedImageError: cannot identify image file &lt;tempfile._TemporaryFileWrapper object at 0x0000021913488130&gt;</div><div class='performance'><p class='time'>Time taken: <wbr>0.00s</p><p class='vram'>Torch active/reserved: 2069/2082 MiB, <wbr>Sys VRAM: 3534/8192 MiB (43.14%)</p></div>"

**Comment by thygate** [comment]
Does the batch processing under the Extras tab work for you, or same issue there ?

**Comment by Marko1985insane** [comment]
Batch processing under the Extras tab works for me.

**Comment by thygate** [comment]
Ok, so it's not something generic with the temporary files or your browser then ..

**Comment by Marko1985insane** [comment]
No, unfortunately not. I tried another browser. Also, for quite a long time it worked fine then suddenly stopped.

**Comment by thygate** [comment]
Ok, this suddenly started happening to me too after updating the webui, I was able to debug it now and fix it.
I will make a commit fixing this in a few minutes ..

**Comment by Marko1985insane** [comment]
It's so bizarre. I updated and tried batch process a whole bunch of times in a row with the same group of four images and then after something like the seventh attempt (and after getting the same errors each time more or less), lo and behold, it worked again and is now working on larger batches too :-D Thanks for your work.

**Comment by thygate** [comment]
It should still work, you're running the A1111 webui right, not some fork ?

**Comment by thygate** [comment]
>AttributeError: 'str' object has no attribute 'name'

wtf, nothing changed but suddenly the gradio element is outputting in a different format again :\

**Comment by thygate** [comment]
You getting that same error ?

Nothing changed, except maybe some packages got auto updated, this is the exact kind of thing why I've always hated python, it's like dll hell all over again :\

**Comment by Marko1985insane** [comment]
I'm not getting the same error and intermittently, I'm getting batch process to work again. I'm pretty sure I'm running the A1111 webui but how would I be sure? (You'll have to use layman's terms as I have no code experience. I followed some detailed online instructions some time ago to install Stable Diffusion soley so I could access your extension as the idea of auto depthmapping and stereoscopic imaging was extremely appealing).

**Comment by thygate** [comment]
Ok, It was a bug after all, It should be fixed now, please update the extension.

**Comment by Marko1985insane** [comment]
Can confirm so far so good after update :-) Thanks for going through the pain!

**Comment by thygate** [comment]
It should be ok now, it was a bug that was introduced (by me) by the custom depth map option.

Is the Batch from directory still not working for you ?

**Comment by Marko1985insane** [comment]
Batch directory has never worked for me and still doesn't work unfortunately.

**Comment by thygate** [comment]
post the error message or stack trace and I might be able to fix it ..

**Comment by Marko1985insane** [comment]
Hey. Here is the latest batch directory error: Error completing request
Arguments: (2, None, None, '"C:\\Users\\Marcos\\Downloads\\Art Folder Batch Scan"', '"C:\\Users\\Marcos\\Downloads\\Art Out"', 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, True, ['left-right'], 3.33, 'polylines_sharp', -0.1, False, False, False, False, False, 'u2net', False, 0, 2, False, None, False, False, True, False) {}
Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Marcos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Marcos\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1146, in run_generate
    image_list = shared.listfiles(depthmap_batch_input_dir)
  File "C:\Users\Marcos\stable-diffusion-webui\modules\shared.py", line 730, in listfiles
    filenames = [os.path.join(dirname, x) for x in sorted(os.listdir(dirname)) if not x.startswith(".")]
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Users\\Marcos\\Downloads\\Art Folder Batch Scan"'

Traceback (most recent call last):
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4307, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\Marcos\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
OSError: [Errno 22] Invalid argument: "<div class='error'>OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: &#x27;&quot;C:\\\\Users\\\\Marcos\\\\Downloads\\\\Art Folder Batch Scan&quot;&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.02s</p><p class='vram'>Torch active/reserved: 2831/2846 MiB, <wbr>Sys VRAM: 4904/8192 MiB (59.86%)</p></div>"

**Comment by thygate** [comment]
> File "C:\Users\Marcos\stable-diffusion-webui\modules\shared.py", line 730, in listfiles

That file doesn't have that many lines .. Are you on the latest version of the webui ?

**Comment by Marko1985insane** [comment]
As far as I know yes. Although I have been reluctant to make any changes for the simple reason, everything is working again with batch process which was my main issue before.

**Comment by Marko1985insane** [comment]
Ok, good to know. As soon as I'm feeling brave enough, I'll risk an update and let you know what happens with it. Thank you.
